### ISSUE TITLE
Brickficiency 2.0.1a doesn't start any more

### ISSUE THREAD

**Issue by falk1010** [WindmillHelix/Brickficiency2#14]
Hi,

I got no response from Brickficiency any more after loading the newest catalog files today.
So I deleted all %appdata%/Brickficiency folders and restarted the program, was asked for my credentials and got the message "Preparing Brickficiency for first use..."
but never "Done...."
CPU-Rate for Brickficiency is 0%

What else can I try?
Any suggestion is welcome!

**Comment by stefbast** [comment]
Same behavior on my machine, no cpu, disk or network activity. Stuck on "Preparing Brickficiency for first use..."

**Comment by esampsonite** [comment]
It's possible (probable) that BrickLink changed something on their side that breaks Brickficiency.  I'm taking a look.

**Comment by esampsonite** [comment]
Well, I traced it back to col17-9 being in the catalog download twice.

You can see it listed on Bricklink twice too: https://www.bricklink.com/v2/search.page?q=col17-9#T=A

This is really their data issue so I posted about it on their forums at https://www.bricklink.com/message.asp?ID=1036950  If it doesn't get addressed promptly I'll add in a workaround for it in Brickficiency.

**Comment by falk1010** [comment]
Hi, thanks for helping.

I just checked the BL-link to col17-9. As it had changed (no duplicate entries any more) I deleted %appdata%/Brickficiency  and therefore forced a reload af the database.
Now it's working again, as expected, THX.

**Comment by esampsonite** [comment]
Awesome, I'm glad that fixed it and thanks for bringing it to my attention.
